# netlify.toml
[build]
  publish = "dist"          # folder to serve
  command = "trunk build" # optional, only if you want Netlify to build automatically

# Redirect all URLs to index.html (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200